apiVersion: v1
kind: Namespace
metadata:
  name: netbird
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbirdio
spec:
  interval: 24h
  url: https://netbirdio.github.io/kubernetes-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
spec:
  interval: 5m
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  chart:
    spec:
      chart: kubernetes-operator
      version: 0.1.x
      sourceRef:
        kind: HelmRepository
        name: netbirdio
      interval: 24h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom: []
