apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metallb/
# patches might need to change depending on the state of
# the docker network.
# Inspect the subnet of the cluster you're using for IP pools.
patches:
  - target:
      kind: IPAddressPool
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 192.168.39.10-192.168.39.15
