apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: grafana-admin
    namespace: monitoring
    files:
      - values.yaml=grafana-admin.enc.yaml
generatorOptions:
  labels:
    reconcile.fluxcd.io/watch: Enabled
