apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: grafana-admin
    namespace: monitoring
    files:
      - admin-user=grafana-admin-user.encrypted
      - admin-password=grafana-admin-password.encrypted
