apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- pvc.yaml

patches:
- target:
    kind: StatefulSet
    name: palworld-server
    namespace: palworld
  patch: |
    - op: add
      path: /spec/template/spec/volumes/0
      value:
        name: backupdir
        persistentVolumeClaim:
          claimName: palworld-backup-pvc
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/0
      value:
        name: backupdir
        mountPath: /palworld/backups
