apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: rook-ceph-values
    namespace: rook-ceph
    files:
      - vaules.yaml=rook-ceph-values.yaml
  - name: rook-ceph-cluster-values
    namespace: rook-ceph
    files:
      - values.yaml=rook-ceph-cluster-values.yaml
