apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: http-ip-allowlist
spec:
  ipAllowList:
    sourceRange:
      - 127.0.0.1/32 # localhost
      - 10.0.0.0/8 # cluster
      - 192.168.0.0/16 # local network
---
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: tcp-ip-allowlist
spec:
  ipAllowList:
    sourceRange:
      - 127.0.0.1/32 # localhost
      - 10.0.0.0/8 # cluster
      - 192.168.0.0/16 # local network
