apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/cert-manager-cloudflare
- ../../../features/tailscale-ha-proxy
components:
- ../../../components/secrets-prod/cert-manager-issuer
