apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/cert-manager-cloudflare
- ../../../features/tailscale-ha-proxy
- ../../../features/rook-ceph-cluster-spec
- ../../../features/rook-ceph-cluster-rbd
- ../../../features/rook-ceph-cluster-fs
- ../../../features/rook-ceph-nfs
- ../../../features/rook-ceph-toolbox
components:
- ../../../components/secrets-prod/cert-manager-issuer
