apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: longhorn-talos-values
  namespace: longhorn-system
  files:
  - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    kind: HelmRelease
    name: longhorn
    namespace: longhorn-values
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: ConfigMap
        name: longhorn-talos-values
