apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/cert-manager
- ../base/netbird
- ../base/traefik
components:
- ../components/netbird-values-testing
- ../components/secrets-testing
- ../../components-common/configs-helm
