apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/traefik
  - ../base/tailscale
components:
  - ../components/tailscale-values-testing
  - ../components/tailscale-secrets
  - ../components/secrets-testing
  - ../../components-common/configs-helm
