apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/metallb
  - ../base/traefik
  - ../base/tailscale
components:
  - ../components/tailnet-patch
  - ../components/tailnet-testing
configurations:
  - ../../../templates/name-reference/kustomizeconfig.yaml
