apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: traefik-values-tailscale
  namespace: ingress
  files:
  - values.yaml=values.yaml

patches:
- target:
    kind: HelmRelease
    name: traefik
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: ConfigMap
        name: traefik-values-tailscale
    - op: add
      path: /spec/dpendsOn
      value:
      - name: tailscale-operator
        namespace: tailscale
