apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: HelmRelease
    name: netbird-operator
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: ConfigMap
        name: netbird-values

configMapGenerator:
- name: netbird-values
  namespace: netbird
  files:
  - values.yaml=values.yaml
