ingress:
  enabled: true
  router:
    enabled: true
  kubernetesAPI:
    enabled: true
    groups:
    - k8s-testing
    policies:
    - kube-api

  policies:
    kube-api:
      name: Netbird admin to kube api
      description: Let's netbird admin access k8s control plane.
      bidirectional: false
      sourceGroups:
      - netbird-admin

    internal-ingress:
      name: Internal ingress access
      desriprtion: Gives srouce groups access to interal apps via ingress
      bidirectional: false
      sourceGroups:
      - netbird-admin

cluster:
  name: k8s-testing
