apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/monitoring/
secretGenerator:
  - name: grafana-admin
    namespace: monitoring
    files:
      - values.yaml=grafana-admin.yaml.encrypted
