apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
resources:
- release.yaml
configMapGenerator:
- name: traefik-values
  namespace: ingress
  files:
  - values.yaml=traefik-values.yaml

