providers:
  kubernetesCRD:
    allowCrossNamespace: true

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
  nfs:
    port: 2049
    expose:
      default: true
    exposedPort: 2049

service:
  type: ClusterIP
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: "k8s-testing"
    netbird.io/policy: "internal-ingress"
