---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgAptBkSEGG30jKuUTI6GgUVGzt6sS2+NKi0IINeeER3jbuH56GemlmPwF8z/62KR0NX7T6Fu6pJGwm07eHpZoKRCR3TE3nW4UsdW8MGPGFqYsf0Xbrhl39PTwfyn1xyXWLmozfGL0mrGplsfKZZjSIfspZDzmJWyyjrHx7ou/UZP/CfuaB09/Uf3p1rQTqc5pPeWaSaokxAc7eRirbnEfCjLiYbEYT4tHAGK/OWZQPRefgarNqX+q2CHb+CbiZBDktF0L/u5yWjLI5fyLopjOv7WLgWsorcDPt3pan3obLLvWpWGIPh/hcF/Yv/Kr3TdQwJfoN1y97ZXYjs3WOMHVlruo153Z5OSYKNnRpud+DQtUjSXePurvu+cwe9AQ+ZzPyOKvDHJigdSvgra1HoCmXprIHi7/robocLvTWavw9R4IUdosfZz1XSZkPC/bk8ntXegMywpZzaymlI0kXdCBCN9aQsnCWgxGojOSja2dr+p9lfeI0zOCg1K6zeNUZQj0RUf/8CtXnCWDG+QSke8F58Qr/CR5DyrX7pwW1LnoIh8TU304TdFMEjH6aJ6G4lKoBENvp+eXi+28cUnJe22Z2sUQC2Ejc+4gNzqgStqciuWYF835YRaXWYc2iLZoXUCVFUtmZzwxMRFrHl+l081mv7IIKjM43UMtFRgiYHWQfl3BcN1tByg8v3Zt8JUT89wZw9KP4YgT3oa3MUTLWv8iTnD/LNmdFUCK7E6dzABgx5Jb/t7xUC4PXmLlpRTkE5AJGGirdIOmAxYpH/jnNVKnoHzzwRjwQ//ltFRpcfYzQL3avg19kxNwzAOYFLY9vMztNiM/s9AXUsg50KpugTs92SG71WJWo=
  template:
    metadata:
      name: tailscale-oauth
      namespace: tailscale
