---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgCMP5giwtKplzX44SZVMnLZXVHVmj0sKTCgUbsZEPBMQrKwHOXjtXKHOjwKU9fDSxE0HFjVApuzSr2VNKHHjTUSKf5KZHaG93OyhJ+WXJ3xoCEtm2nVeH6BNGbZcH8/euMSc0PuPPHid+aKmG8cYgnGdf9ay0Val2MkHb/FxlZUUh4vITgRaxV3rOeIC1w+GmYkCCcJvHjN7pKigHYWC99pKeU2uDKWyFeLA2+O7aMawTFDarnEqHonoJdkwI3u2a35d4MjTZ8tUSKmENCmOx47p/5TxPFAZhBzcwVFZndPyAvXpag3jVjEMqa3OKAIJSMdo6+ttmdJAqQT8IpAPvRda9cmzZ4i6vTLYxQNtxLNkx0DPuw5p+Jj9D0LTvs1UYgPxip9NFFxWUd90PjVEZxMovrjAWMt1/ZCkqFPd4N1t2k5PxbidyEv3OIKqwbvH4Fdkh1I9OMlOWCJyXlJqz28cA8xEtpJqmxKkFaKCVzHWEUOz5vTmDecVSkEGtvaddCI0kEHXHxOIHEsAKQw6tv1BxM6Bh5Jz0cBRnlfIUA3oyXIvCCI4Jyx2ggv8rK/HXakO4nSagRNBo+NCH1E23vUUZxfMygpWCF50WgYrMHolrMhQ6vN50pM9XssvBVR1LGpXMu1ruxJvszjNTOwa96zW7AGkgYFYGbyPsyExc2VwHaO31muoBu98OqgnMYvhQsuym3S0mWuOHPAHmZUuzVig30b2fWqVkB05FNIaU0y0dB1EM7e7YXG9QqYxvLVtXCWC+x8G9+M6P9iE8U1fkvgDHB6dE1qf2NKlU3oEg5ORZCwSTSBdNVU0pvXouqealXc1F7UQcBoUUgBwZiUja1tCMMp87c=
  template:
    metadata:
      name: tailscale-oauth
      namespace: tailscale
