apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
- name: tailnet-credentials
  namespace: tailscale
  files:
  - values.yaml=client.enc.yaml

patches:
- target:
    kind: HelmRelease
    name: tailscale-operator
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: Secret
        name: tailnet-credentials
