apiVersion: v1
kind: Service
metadata:
  name: traefik-int
  namespace: ingress
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: websecure
    port: 443
    targetPort: websecure
  selector:
    app.kubernetes.io/name: traefik
  type: LoadBalancer
  loadBalancerClass: tailscale
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ext
  namespace: ingress
spec:
  ports:
  - name: web-ext
    port: 80
    targetPort: web-ext
  - name: websecure-ext
    port: 443
    targetPort: websecure-ext
  selector:
    app.kubernetes.io/name: traefik
  type: LoadBalancer
