apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-ingress
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`home.int.noodoodle.us`)
    services:
    - name: home-assistant
      namespace: home-assistant
      port: http
