apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- vpn-login.yaml
patches:
- target:
    kind: Deployment
    name: deluge
    namespace: media-stack
  patch: |
    - op: add
      path: /spec/template/spec/initContainers/0/envFrom
      value:
      - secretRef:
          name: deluge-auth

