apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: tunnel-token
    namespace: cloudflared
    files:
      - token=cloudflared.enc
  - name: pihole-secrets
    namespace: pihole
    files:
      - values.yaml=pihole-secrets.enc.yaml
