- op: add
  path: /spec/values
  value:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
      hosts:
        - grafana.noodoodle.us
- op: add
  path: /spec/valuesFrom
  value:
    - kind: Secret
      name: grafana-secret
      valuesKey: adminPassword
      targetPath: /grafana/adminPassword
    - kind: Secret
      name: grafana-secret
      valuesKey: adminUser
      targetPath: /grafana/adminUser
