apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    adminUser: ENC[AES256_GCM,data:dqiw2Cc=,iv:RumWvUKREz6XA7u+V/HDLqf7SRlp+DuLPIczjvcVcz4=,tag:IemtMbbrHDu/JsmUEBDJkA==,type:str]
    adminPassword: ENC[AES256_GCM,data:UeNf4Rvu0rXbFWySSd2g4Q==,iv:oUslOx0cqFcimhiF6+NNep3zZIgn3RHuY9hMkIUw/mQ=,tag:x+FsFfkvJ1IeEMG9KECK6Q==,type:str]
sops:
    age:
        - recipient: age166s585p6wc3yurjx0a64v9xfw0lfquknt8ewpyqwq4uq7uyqdfpsrde3c8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSmdXR0RzZnpMZVg0LzJX
            aWNOSWRBT3UrTTNpdThtOEZCV0hydy9GeEJrClZTdTgzcjNsU3lsYkVzQVJGcHRI
            UTJLRnI3bDNlNW8yQlE0Q09menZ5V3cKLS0tIDB2VmdXRkpTQkY5NndGR0lvbU1w
            Rkd3dmNnMWtZVm52MkhXSVNBcWl2OGMKSPBcROQ0NJWNlyginOszEB4tk2YbX0Ig
            NHTKfPgK6pay1fmjA4BvhyxwJ04gCQh+QcuCGiy1PckIpqU8XHU7RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T21:37:47Z"
    mac: ENC[AES256_GCM,data:KDqZ5M8fB5zFirTjUwHrulVZz/StMlB5JSTwHxQf7mRgH9eF0Pg2bF4b0d6FoITY7nejjT9JO6pZNaUmMoM2s2o1sOmzCfca5Hpyogcvu7JWydyiOly8kFlGFNN+6H7UEE2wTfLnYUgqoabp4iSWj9hWBT9EZCqo7LbplSaTEiI=,iv:6A2zVavjDK6mtLpfYa9gD67vQCwYYqzvzYqvf7zyurQ=,tag:vAB9jFBs+kXM8x48hoiSBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
