apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    grafana:
        adminUser: ENC[AES256_GCM,data:pqqLG2w=,iv:swi4m1sjI3O8YiRwg5/Hh2/Il7KV0WvvAPuV1686AmA=,tag:tlFOBB5iRI+ATrpGZ0hVSA==,type:str]
        adminPassword: ENC[AES256_GCM,data:fFMlBiKe55OThIfupNi7Uw==,iv:4vAZoJU0bFpgm7y2r1ims1iHXFASXZFkrVtKQCjdMaM=,tag:vuJ2/OxiaCraGT4MJHPvcA==,type:str]
sops:
    age:
        - recipient: age166s585p6wc3yurjx0a64v9xfw0lfquknt8ewpyqwq4uq7uyqdfpsrde3c8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSmdXR0RzZnpMZVg0LzJX
            aWNOSWRBT3UrTTNpdThtOEZCV0hydy9GeEJrClZTdTgzcjNsU3lsYkVzQVJGcHRI
            UTJLRnI3bDNlNW8yQlE0Q09menZ5V3cKLS0tIDB2VmdXRkpTQkY5NndGR0lvbU1w
            Rkd3dmNnMWtZVm52MkhXSVNBcWl2OGMKSPBcROQ0NJWNlyginOszEB4tk2YbX0Ig
            NHTKfPgK6pay1fmjA4BvhyxwJ04gCQh+QcuCGiy1PckIpqU8XHU7RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T21:27:04Z"
    mac: ENC[AES256_GCM,data:TqNMRSAmsiFoTRYA3RG0O3PheSmgT6kFC7fFR52Ig7pnC3Q7JK6vRNDWC9R/zWxiaxthm72VNeO1Ha9iSP9I6DH/9zBsW+rcEo4BfvCC0ir9eZrsZFNeIiwKML5mwnih/loKJhu1fLMOJviPim5mGey0d0ql36L4B3Y2jR8Q3rU=,iv:c0Q5c0PnWWHBEa9MPS5QAoeZ43+YcITUbLDcSLtcmzg=,tag:IC0JDa2ZObkDsAY63LX4QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
