apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    adminUser: ENC[AES256_GCM,data:dw2/ysc=,iv:K2RNGprl9q6G83oz0KW+TKnPX/Xsbevyk6HjjvKjnFI=,tag:RIZr6Cv06uB4XnQ2gIl3wQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:3Ht6TbSf0Qf/yIm2gYhBQg==,iv:KlMi5QUbDQpHfmZqVwZ4BJwqoX5TRj6sOZ4u4I/209c=,tag:3+8xzjo6xe5tkQdcqz1imQ==,type:str]
sops:
    age:
        - recipient: age166s585p6wc3yurjx0a64v9xfw0lfquknt8ewpyqwq4uq7uyqdfpsrde3c8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSmdXR0RzZnpMZVg0LzJX
            aWNOSWRBT3UrTTNpdThtOEZCV0hydy9GeEJrClZTdTgzcjNsU3lsYkVzQVJGcHRI
            UTJLRnI3bDNlNW8yQlE0Q09menZ5V3cKLS0tIDB2VmdXRkpTQkY5NndGR0lvbU1w
            Rkd3dmNnMWtZVm52MkhXSVNBcWl2OGMKSPBcROQ0NJWNlyginOszEB4tk2YbX0Ig
            NHTKfPgK6pay1fmjA4BvhyxwJ04gCQh+QcuCGiy1PckIpqU8XHU7RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T22:10:27Z"
    mac: ENC[AES256_GCM,data:SCdrcMJJvK7f9NPqW0fZ40NIaD0nEuZ34hTk0Z8rdudjdXUP0kL8IlQVKXUA8B4TyGtE2abixiDJEQAorZpB11vcVmAi/YahxKkneZdcl/Du7ETsfX7vE5I94d+fYeP7QhjWaLWrDfcLfpH75OzJM6Q7r7OYB6XOQ5QDxcKWgDA=,iv:zAqfgEDC5c2DDLJ3447AftYCTDulpf0stN8Llzl4NWs=,tag:88wYaeXyXgyIncqb7Qj04Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
