apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/kube-pormetheus-stack
patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: replace
        path: /spec/values/grafana
        value:
          ingress: true
          hosts: [grafana.noodoodle.us]
