apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/kube-pormetheus-stack
patches:
  - target:
      kind: HelmRelease
      patch:
        - values:
            grafana:
              ingress: true
              hosts:
                - grafana.noodoodle.us
