apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: traefik-gateway
spec:
  routes:
  - match: Host(`grafana.ts.noodoodle us`)
    services:
    - name: kube-prometheus-stack-grafana
      namespace: monitoring
      port: 80
