apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
configMapGenerator:
  - name: rook-ceph-cluster-values
    namespace: rook-ceph
    files:
      - values.yaml=cluster-values.yaml
