apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../../../features/rook-ceph-operator
# - ../../../features/rook-ceph-cluster
- ../../../features/secrets
components:
# - ../../../components/rook-ceph-values-nix
# - ../../../components/rook-ceph-values-prod
