apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/reloader
- ../../../features/secrets
- ../../../features/rook-ceph-operator
- ../../../features/rook-ceph-cluster
components:
- ../../../components/rook-ceph-values-prod
