oauth:
    clientId: ENC[AES256_GCM,data:vb9n7EbmPtCXzVbWbRVVgHs=,iv:Wc2gb1+8haYKUf6dWjUTTbuJ1c3juT0tAVKP0L/gvGk=,tag:tQQcj/uA7g4W/2Y0fRmLcw==,type:str]
    clientSecret: ENC[AES256_GCM,data:K8FsxTXi7z9dsUJXTcMQSc2iZrBSkF1IDx5bH9TMVPqKezd21gKjT6eQ1iPMw5uWRdcbP1P14gA+v+gzsdRD,iv:Iy2tLT6q0uekppnCM1lUvu5wf+X0zIzSJfDBYbRQAb0=,tag:x8gtAlpsE6Onis78pGHtsg==,type:str]
sops:
    age:
        - recipient: age1hx49ntpympqcutqwrcrd6u4pggug99pxuy794vcx8us35hcp73vs3dctf5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUmhYblp6OGdqS1Y3aTdt
            K3k2UENhdDNFcEF0Wm0yMUJNQ3JXeGlKa0RJCm5mS1F3RnVxL1RPWk9RRmtFc1Vo
            dnYxMWpJdi9iMXNEcVFFbjVOb3FIOXcKLS0tIE9SL2ttQng1YnBjUWJxaThZWHpo
            SGIwYmtZbUlLQ0pRK3dWQVVOOGM3NUEKKds2U0J5gl70Qz4JyDgYeXhbi/fh9QMa
            Yi31dmd07F+0ule6jxR6xODv9esy08b2VpupLqLfiZwMNQwS0G2TDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T17:18:41Z"
    mac: ENC[AES256_GCM,data:baPNyMYdV3iVP+smyasdVV9ivWmqL9dmacICiMaSU3H1kSvVpDkA0NA3VMdS+U2RwQ91kX1kuyIADz0l0O6GL8iOYiPE4/hHU3G/qvk/an5+TGQQrNpObFx7dOLmHyEFDL2Xzn4Fm5SWc237eKRSMgnz/lrMvYnNbetUC6Gv+cs=,iv:ch+jRxPyHJ1gmbbjajAlIRv71kIBCS/tm3OSGvePXbs=,tag:EAjc52E6656fH5v4WWpkDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
