apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: palworld-maintenance
  name: palworld-maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palworld-maintenance
  template:
    metadata:
      labels:
        app: palworld-maintenance
    spec:
      containers:
      - image: busybox:latest@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
        name: busybox
        command:
        - /bin/sh
        args:
        - "-c"
        - "sleep 3600"
        volumeMounts:
        - name: datadir
          mountPath: /palworld
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: palworld-pvc-palworld-server-0
