apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: palworld-maintenance
  name: palworld-maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palworld-maintenance
  template:
    metadata:
      labels:
        app: palworld-maintenance
    spec:
      containers:
      - image: busybox:latest@sha256:2383baad1860bbe9d8a7a843775048fd07d8afe292b94bd876df64a69aae7cb1
        name: busybox
        command:
        - /bin/sh
        args:
        - "-c"
        - "sleep 3600"
        volumeMounts:
        - name: datadir
          mountPath: /palworld
        - name: backupdir
          mountPath: /palworld/backups
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: palworld-pvc
      - name: backupdir
        persistentVolumeClaim:
          claimName: palworld-backup-pvc
