apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/lb-address-pools
  - ../base/rook-ceph-nfs
  - ../base/middlewares
components:
  - ../components/context-minikube
