apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/metallb
- ../../../features/monitoring
- ../../../features/pihole
- ../../../features/tailscale
- ../../../features/traefik
components:
- ../../../components/pihole-values
- ../../../components/tailscale-values-testing
- ../../../components/traefik-values-testing
- ../../../components/secrets-testing/tailscale-api
- ../../../components/namerefs-helm
