apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/lb-address-pools
  - ../base/monitoring
  - ../base/pihole
  - ../base/wireguard
patches:
  - path: k3d.yaml
    target:
      kind: IPAddressPool
