apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/monitoring
  - ../base/lb-address-pools
  - ../base/pihole
components:
  - ../../components-common/configs-helm
  - ../components/context-k3d
