apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/cert-manager
- ../../../features/secrets
- ../../../features/tailscale
- ../../../features/traefik
components:
- ../../../components/secrets-testing/tailscale-auth
- ../../../components/traefik-values
- ../../../components/tailscale-values-testing
- ../../../components/namerefs-helm
