apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/metallb
- ../../../features/traefik
components:
- ../../../components/traefik-values
- ../../../components/namerefs-helm
