apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/lb-address-pools
  - ../base/middlewares
  - ../base/monitoring
  - ../base/pihole
  - ../base/wireguard
components:
  - ../components/context-minikube
