apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/reloader
- ../../../features/traefik
- ../../../features/traefik-tailscale-svc
- ../../../features/tailscale
components:
- ../../../components/traefik-values
- ../../../components/traefik-values-tailscale
- ../../../components/tailscale-values-dev
- ../../../components/secrets-testing/tailscale-auth
