apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: pihole-values
    namespace: pihole
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true

patches:
- target:
    kind: HelmRelease
    name: pihole
    namespace: pihole
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: ConfigMap
        name: pihole-values
