apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: syncthing-ingress
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`syncthing.int.noodoodle.us`)
    services:
    - name: syncthing-web
      namespace: syncthing
      port: http
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-web
spec:
  selector:
    app: syncthing
  ports:
  - name: http
    port: 80
    targetPort: 8384
