providers:
  kubernetesCRD:
    allowCrossNamespace: true

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
  nfs:
    expose:
      default: true
    port: 2049
    exposedPort: 2049

  pals:
    expose:
      default: false
    port: 8211
    exposedPort: 8211
    protocol: UDP

  web-ext:
    expose:
      default: false
    exposedPort: 7080
    port: 7080
    redirections:
      entryPoint:
        to: websecure-ext

  websecure-ext:
    expose:
      default: false
    exposedPort: 7443
    port: 7443
    tls:
      enabled: true
