apiVersion: v1
kind: Service
metadata:
  name: traefik-int
  namespace: ingress
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: websecure
    port: 443
    targetPort: websecure
  - name: nfs
    port: 2049
    targetPort: nfs
  - name: pals
    port: 8211
    protocol: UDP
    targetPort: pals
  selector:
    app.kubernetes.io/name: traefik
  type: LoadBalancer
  loadBalancerClass: tailscale
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ext
  namespace: ingress
spec:
  ports:
  - name: web-ext
    port: 80
    targetPort: web-ext
  - name: websecure-ext
    port: 443
    targetPort: websecure-ext
  selector:
    app.kubernetes.io/name: traefik
  type: ClusterIP
