apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/rook-ceph-cluster-spec
- ../../../features/rook-ceph-cluster-rbd
- ../../../features/rook-ceph-cluster-fs
- ../../../features/rook-ceph-nfs
- ../../../features/tailscale-ha-proxy
components:
- ../../../components/rook-ceph-values-dev
