apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deluge
    storage: media-stack
    security: lscr
  name: deluge
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      initContainers:
      - image: qmcgaw/gluetun:v3.41.0
        name: gluetun
        restartPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      containers:
      - image: lscr.io/linuxserver/deluge:2.2.0@sha256:ec3439ea597eea2eef8f14eb7fbfa0f888cb2ad06c47cb165fc9f86f4f336ac3
        name: deluge
        ports:
        - name: http
          containerPort: 8112
        - containerPort: 6881
        - containerPort: 6881
          protocol: UDP
        volumeMounts:
        - name: configdir
          mountPath: /config
      volumes:
      - name: configdir
        persistentVolumeClaim:
          claimName: deluge-config-pvc
