apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deluge
    storage: media-stack
    security: lscr
  name: deluge
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deluge
    spec:
      initContainers:
      - image: qmcgaw/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
        name: gluetun
        restartPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      containers:
      - image: lscr.io/linuxserver/deluge:18.04.1@sha256:0ac8716243944d28890565f759c7cedfc9e36a3fd5a827c9d0927abc0c8f97c9
        name: deluge
        ports:
        - name: http
          containerPort: 8112
        - containerPort: 6881
        - containerPort: 6881
          protocol: UDP
        volumeMounts:
        - name: configdir
          mountPath: /config
      volumes:
      - name: configdir
        persistentVolumeClaim:
          claimName: deluge-config-pvc
