apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deluge
  name: deluge
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  template:
    metadata:
      labels:
        app: deluge
    spec:
      initContainers:
      - image: qmcgaw/gluetun:v3.41.0@sha256:6b54856716d0de56e5bb00a77029b0adea57284cf5a466f23aad5979257d3045
        name: gluetun
        restartPolicy: Always
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        envFrom: []
      - image: busybox:latest@sha256:2383baad1860bbe9d8a7a843775048fd07d8afe292b94bd876df64a69aae7cb1
        name: deluge-data-init
        command:
        - "/bin/sh"
        - "-c"
        - |
          mkdir -p /data/deluge/completed
          mkdir -p /data/deluge/incomplete
          mkdir -p /data/deluge/torrents
          chown 1000 -R /data/deluge
        volumeMounts:
        - name: datadir
          mountPath: /data
      containers:
      - image: lscr.io/linuxserver/deluge:2.2.0@sha256:ec3439ea597eea2eef8f14eb7fbfa0f888cb2ad06c47cb165fc9f86f4f336ac3
        name: deluge
        ports:
        - name: http
          containerPort: 8112
        - containerPort: 6881
        - containerPort: 6881
          protocol: UDP
        envFrom:
        - configMapRef:
            name: linux-server-io-env
        volumeMounts:
        - name: configdir
          mountPath: /config
        - name: datadir
          mountPath: /data
      volumes:
      - name: configdir
        persistentVolumeClaim:
          claimName: deluge-config-pvc
      - name: datadir
        persistentVolumeClaim:
          claimName: media-stack-pvc
