apiVersion: v1
kind: Service
metadata:
  name: deluge-web
spec:
  selector:
    app: deluge
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: deluge-ingress
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`deluge.ts.noodoodle.us`)
    services:
    - name: deluge-web
      namespace: media-stack
      port: 80
