apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: immich-values
  namespace: immich
  files:
  - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
- target:
    kind: HelmRelease
    name: immich
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: ConfigMap
        name: immich-values
