apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/rook-ceph-nfs/
patches:
  - target:
      kind: MiddlewareTCP
    patch: |
      - op: replace
        path: /spec/ipAllowList/sourceRange
        value:
          - 172.17.0.1/16
          - 10.244.0.1/16
