apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/cert-manager
- ../../../features/metallb
- ../../../features/monitoring
- ../../../features/pihole
- ../../../features/secrets
- ../../../features/tailscale
- ../../../features/traefik
components:
- ../../../components/pihole-values
- ../../../components/tailscale-values-staging
- ../../../components/traefik-values
- ../../../components/secrets-staging/tailscale-auth
- ../../../components/namerefs-helm
