apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/metallb-address-pools
- ../../../features/rook-ceph-nfs
- ../../../features/tailscale-ha-proxy
components:
- ../../../components/metallb-k3d
