apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/metallb-address-pools
- ../../../features/rook-ceph-nfs
components:
- ../../../components/metallb-minikube
