apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - namespace.yaml
  - repo.yaml
  - operator-release.yaml
  - cluster-release.yaml
configurations:
  - ../../../templates/name-reference/kustomizeconfig.yaml
