apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metallb/
patches:
  - target:
      kind: IPAddressPool
    patch:
      - op: replace
        path: /spec/addresses
        value:
          - 172.28.0.10-172.28.0.30
