apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/traefik-dash-ingress
- ../../../features/rook-ceph-ingress
components:
- ../../../components/dashboards-tls
