apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: media-stack-ingress
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`bazarr.int.noodoodle.us`)
    services:
    - name: bazarr-web
      namespace: media-stack
      port: 80
  - match: Host(`prowlarr.int.noodoodle.us`)
    services:
    - name: prowlarr-web
      namespace: media-stack
      port: 80
  - match: Host(`radarr.int.noodoodle.us`)
    services:
    - name: radarr-web
      namespace: media-stack
      port: 80
  - match: Host(`sonarr.int.noodoodle.us`)
    services:
    - name: sonarr-web
      namespace: media-stack
      port: 80
