apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-stack
resources:
- svc.yaml
- ingress.yaml
# deployments
- bazarr.yaml
- flaresolverr.yaml
- prowlarr.yaml
- radarr.yaml
- sonarr.yaml
