apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-deployment
  labels:
    app: wireguard
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: wireguard
  template:
    metadata:
      labels:
        pod: wireguard
    spec:
      containers:
        - image: lscr.io/linuxserver/wireguard:latest
          name: wireguard
          ports:
            - containerPort: 51820
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: PEERS
              value: "3"
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: wg-config
              mountPath: /config
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: wireguard-pvc
