apiVersion: v1
kind: Service
metadata:
  name: wireguard-svc
spec:
  type: ClusterIP
  ports:
    - name: udp
      port: 51820
      protocol: UDP
  selectors:
    app: wireguard
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: wireguard-ingress
spec:
  entryPoints:
    - wireguard
  routes:
    - match: HostSNI(`*`)
      services:
        - name: wireguard-svc
          port: 51820
          nativeLB: true
      middlewares:
        - name: udp-ip-allowlist
          namespace: traefik-gateway
