apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- app-config.yaml
patches:
- target:
    kind: HelmRelease
    namespace: arc-runners
    name: arc-runners
  patch: |
    - op: add
      path: /spec/valuesFrom/0
      value:
        kind: Secret
        name: arc-app-auth
