apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/media-stack-deps
- ../../../features/jellyfin
components:
- ../../../components/media-stack-storage
- ../../../components/media-stack-security-context
