apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/deluge
- ../../../features/media-stack-deps
- ../../../features/media-stack
- ../../../features/jellyfin
components:
- ../../../components/lscr-security-context
- ../../../components/media-stack-storage
- ../../../components/secrets-dev/deluge-auth
