apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/rook-ceph-ingress
- ../../../features/syncthing
components:
- ../../../components/dashboards-dev
- ../../../components/lscr-security-context
