apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/palworld
- ../../../features/rook-ceph-ingress
components:
- ../../../components/palworld-security-context
- ../../../components/palworld-values
- ../../../components/secrets-dev/palworld-auth
