apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/home-assistant
components:
- ../../../components/home-assistant-values
- ../../../components/dashboards-dev
