apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/palworld
components:
- ../../../components/secrets-dev/palworld-auth
- ../../../components/palworld-values
