apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/immich
- ../../../features/syncthing
components:
- ../../../components/immich-values
- ../../../components/lscr-security-context
