apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-gateway
resources:
  - release.yaml
configMapGenerator:
  - name: traefik-values
    namespace: traefik-gateway
    files:
      - values.yaml=traefik-values.yaml

