apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  # basic options
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovateapp.com>
  RENOVATE_PLATFORM: github
  # directory changes
  RENOVATE_BASE_DIR: /tmp/renovate/
  RENOVATE_CONFIG_FILE: /opt/renovate/config.yaml
