apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
configMapGenerator:
  - name: grafana-values
    namespace: monitoring
    files:
      - vales.yaml=grafana-values.yaml
secretGenerator:
  - name: grafana-admin
    namespace: monitoring
    files:
      - values.yaml=grafana-admin.enc.yaml
