apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: IngressRoute
      labelSelector: "ingress=local"
    patch: |
      - op: add
        path: /spec/routes/0
        value:
          middlewares:
            - name: http-ip-allowlist
              namespace: traefik-gateway
