apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/actions-runner-controller
- ../../../features/actions-runner-mathing
- ../../../features/cert-manager
- ../../../features/cloudnative-pg
- ../../../features/rook-ceph-operator
- ../../../features/tailscale
- ../../../features/traefik
- ../../../features/traefik-tailscale-svc
components:
- ../../../components/secrets-prod/arc-auth
- ../../../components/secrets-prod/tailscale-oauth
- ../../../components/tailscale-values-prod
- ../../../components/traefik-values
- ../../../components/traefik-values-tailscale
