apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/cert-manager-cloudflare
- ../../../features/metallb-address-pools
- ../../../features/rook-ceph-nfs
- ../../../features/tailscale-ha-proxy
components:
- ../../../components/metallb-minikube
- ../../../components/secrets-staging/cert-manager-issuer
