apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../templates/rook-ceph-toolbox.yaml
patches:
  - target:
      kind: Job
    patch: |-
      - op: replace
        path: /metadata/name
        value: rook-ceph-nfs-export-job
      - op: replace
        path: /spec/template/spec/containers/0/command
        value: |
          - "bash"
          - "-c"
          - |
            ceph mgr module enable rook
            ceph mgr module enable nfs
            ceph orch set backend rook
            ceph nfs export create cephfs test /test ceph-filesystem
