apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      initContainers:
      - name: jellyfin-data
        image: busybox:latest@sha256:2383baad1860bbe9d8a7a843775048fd07d8afe292b94bd876df64a69aae7cb1
        command:
        - "/bin/sh"
        - "-c"
        - |
          mkdir -p /data/jellyfin/anime
          mkdir -p /data/jellyfin/movies
          mkdir -p /data/jellyfin/tv
          chown 1000 -R /data/jellyfin
        volumeMounts:
        - name: datadir
          mountPath: /data
      containers:
      - image: lscr.io/linuxserver/jellyfin:10.11.6@sha256:df1ccfdd214c39c9ae0595b5800591b52a6f87bbbab1bd4a53dc7be6852cf6b1
        name: jellyfin
        envFrom:
        - configMapRef:
            name: linux-server-io-env
        ports:
        - name: http
          containerPort: 8096
        - name: local-udp
          containerPort: 7359
          protocol: UDP
        volumeMounts:
        - name: configdir
          mountPath: /config
        - name: datadir
          subPath: jellyfin
          mountPath: /data
      volumes:
      - name: configdir
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: datadir
        persistentVolumeClaim:
          claimName: media-stack-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
