apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ceph-ingress
  namespace: ingress
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`ceph.int.noodoodle.us`)
    services:
    - name: rook-ceph-mgr-dashboard
      namespace: rook-ceph
      port: 7000
