apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: HelmRelease
      name: tailscale-operator
      namespace: tailscale
    patch: |
      - op: add
        path: /spec/valuesFrom/0
        value:
          kind: ConfigMap
          name: tailscale-values

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: tailscale-values
    namespace: tailscale
    files:
      - values.yaml=values.yaml
