apiVersion: v1
kind: Service
metadata:
  name: linkding-svc
spec:
  type: ExternalName
  externalName: linkding-svc.cloudflared.svc.cluster.local
  selector:
    app: linkding
  ports:
    - port: 9090
