apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metallb/
patches:
  - target:
      kind: IPAddressPool
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 192.168.39.10-192.168.39.30
