operatorConfig:
  defaultTags:
    - "tag:k8s-operator"
    - "tag:testing"
  hostname: "tailscale-operator-testing"

proxyConfig:
  defaultTags: "tag:k8s,tag:testing"

apiServerProxyConfig:
  allowImpersonation: "true"
  mode: "true"
