apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-server-values
  namespace: palworld
data:
  TZ: America/New_York
  PLAYERS: "4"
  PORT: "8211"
  QUERY_PORT: "27015"
  REST_API_PORT: "8212"
  PUID: "1000"
  PGID: "1000"
  MULTITHREADING: "false"
  COMMUNITY: "false"
  PUBLIC_IP: ""
  PUBLIC_PORT: ""
  # Server info
  SERVER_NAME: jontopia
  SERVER_DESCRIPTION: ""
  UPDATE_ON_BOOT: "true"
  RCON_ENABLED: "false"
  RCON_PORT: "25575"
  # Backups
  BACKUP_ENABLED: "true"
  DELETE_OLD_BACKUPS: "true"
  OLD_BACKUP_DAYS: "30"
  BACKUP_CRON_EXPRESSION: "0 5 * * 1"
  # Auto update
  AUTO_UPDATE_ENABLED: "false"
  AUTO_UPDATE_CRON_EXPRESSION: "0 * * * *"
  AUTO_UPDATE_WARN_MINUTES: "30"
  # Auto reboot
  AUTO_REBOOT_ENABLED: "false"
  AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE: "false"
  AUTO_REBOOT_WARN_MINUTES: "5"
  AUTO_REBOOT_CRON_EXPRESSION: "0 0 * * *"
  # Auto pause
  AUTO_PAUSE_ENABLED: "false"
  AUTO_PAUSE_TIMEOUT_EST: "180"
  AUTO_PAUSE_LOG: "true"
  AUTO_PAUSE_DEBUG: "false"
  ENABLE_PLAYER_LOGGING: "true"
  PLAYER_LOGGING_POLL_PERIOD: "5"
