apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-gameplay-values
  namespace: palworld
data:
  # General settings
  AUTO_SAVE_SPAN: "30.000000"
  # Player settings
  DEATH_PENALTY: "None"
  EXP_RATE: "2.000000"
  # Pal settings
  ALLOW_GLOBAL_PALBOX_EXPORT: "True"
  ALLOW_GLOBAL_PALBOX_IMPORT: "True"
  PAL_EGG_DEFAULT_HATCHING_TIME: "1.00000"
  # Building settings
  BUILD_AREA_LIMIT: "False"
  BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: "0.000000"
  MAX_BUILDING_LIMIT_NUM: "0"
  # Base & Guild settings
  BASE_CAMP_WORKER_MAX_NUM: "15"
  BASE_CAMP_MAX_NUM_IN_GUILD: "6"
  GUILD_PLAYER_MAX_NUM: "20"
  SHOW_PLAYER_LIST: "True"
  # Items and equipment settings
  SUPPLY_DROP_SPAN: "180"
  # Enemy settings
  ENABLE_INVADER_ENEMY: "True"
  ENABLE_PREDATOR_BOSS_PAL: "True"
