apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../actions-runner-template
patches:
- target:
    kind: HelmRelease
  patch: |
    - op: replace
      path: /metadata/name
      value: arc-runners
    - op: add
      path: /spec/values
      value:
        githubConfigUrl: https://github.com/GianniBuoni/arc-demo
