apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/renovate
components:
- ../../../components/renovate-config
- ../../../components/secrets-testing/renovate-auth
