apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/actions-runner-controller
- ../../../features/actions-runner-scale-set
components:
- ../../../components/secrets-dev/arc-auth
