apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: testing-cluster
  namespace: tailscale
spec:
  type: kube-apiserver
  replicas: 3
  tags:
    - tag:k8s
  kubeAPIServer:
    mode: noauth
