apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../features/rook-ceph-toolbox
- ../../../features/renovate
components:
- ../../../components/rook-ceph-nfs-export
- ../../../components/renovate-config
- ../../../components/secrets-testing/renovate-auth
